# Generated by Django 5.0.6 on 2024-07-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, help_text='Required, unique', max_length=50, null=True, verbose_name='Product Website ID')),
                ('slug', models.SlugField(blank=True, help_text='Required, letters, numbers, underscores, or hyphens', max_length=255, verbose_name='Product Safe URL')),
                ('name', models.CharField(help_text='Required, max 255 characters', max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(help_text='Required', verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Required, max 99999999.99', max_digits=10, verbose_name='Product Price')),
                ('is_active', models.BooleanField(default=True, help_text='True = Product Visible', verbose_name='Product Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Format: Y-m-d H:M:S', verbose_name='Date Product Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Format: Y-m-d H:M:S', verbose_name='Date Product Last Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='myapp_produ_id_6ea60b_idx'), models.Index(fields=['name'], name='myapp_produ_name_2e356a_idx'), models.Index(fields=['-created_at'], name='myapp_produ_created_e3d47d_idx')],
            },
        ),
    ]
