# Generated by Django 5.0.6 on 2024-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Required, letters, numbers, underscores, or hyphens', max_length=255, verbose_name='Product Safe URL'),
        ),
    ]
